// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerminRessourcenPlaner.Data;

#nullable disable

namespace TerminRessourcenPlaner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109103444_TerminUmDienstleistungErweitern")]
    partial class TerminUmDienstleistungErweitern
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Dienstleistung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DauerInMinuten")
                        .HasColumnType("int");

                    b.Property<string>("Kategorie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("PreisInEuro")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Dienstleistung");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Ressource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ressourcen");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("longtext");

                    b.Property<int>("DienstleistungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ende")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kundenname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DienstleistungId");

                    b.ToTable("Termine");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.TerminRessource", b =>
                {
                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.Property<int>("RessourceId")
                        .HasColumnType("int");

                    b.HasKey("TerminId", "RessourceId");

                    b.HasIndex("RessourceId");

                    b.ToTable("TerminRessourcen");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Termin", b =>
                {
                    b.HasOne("TerminRessourcenPlaner.Models.Dienstleistung", "Dienstleistung")
                        .WithMany()
                        .HasForeignKey("DienstleistungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dienstleistung");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.TerminRessource", b =>
                {
                    b.HasOne("TerminRessourcenPlaner.Models.Ressource", "Ressource")
                        .WithMany("TerminRessourcen")
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerminRessourcenPlaner.Models.Termin", "Termin")
                        .WithMany("TerminRessourcen")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ressource");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Ressource", b =>
                {
                    b.Navigation("TerminRessourcen");
                });

            modelBuilder.Entity("TerminRessourcenPlaner.Models.Termin", b =>
                {
                    b.Navigation("TerminRessourcen");
                });
#pragma warning restore 612, 618
        }
    }
}
